
version: '3'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  mongodb:
    image: push mayuriswan/demo-app:node-1.0
    ports:
      - 8000:8000
    
    
  mongo-express:
    image: postgres:13
    
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:my-ps
    
